name: Browserstack CI Integration
on: [push]
env:
        BROWSERSTACK_ACCESS_KEY: "${{ secrets.chDzgheXDyQmy95wW4GQ }}"
        BROWSERSTACK_USERNAME: "${{ secrets.ajithkumar_O5LtPf }}"
jobs:
  test:
    name: browserstack test
    runs-on: windows-latest
    steps:
      - name: Browserstack actions
        uses:  browserstack/github-actions@v1.0.1
        with:
          username: ajithkumar_O5LtPf
          access-key: chDzgheXDyQmy95wW4GQ     
