name: 'BrowserStack Env Setup'
uses: 'browserstack/github-actions/setup-env@master'
with:
     username:  ${{ secrets.ajithkumar_O5LtPf }}
     access-key: ${{ secrets.chDzgheXDyQmy95wW4GQ }}
     build-name: 'TEST'
     project-name: 'AUTOMATIONLOGIN'


